### PR TITLE
fix: fixes site tools ignored

### LINKED ISSUE #58: bug: some tools enabled are ignored
http, zap, testssl tools enabled in general but ignored by action scans.
Sample: https://github.com/MTES-MCT/dashlord-dgaln/actions/runs/1228422789

### PR DESCRIPTION
**Pull request by tristanrobert**
Fixes #58

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -22,7 +22,9 @@ type DashlordTool =
   | "dependabot"
   | "codescan"
   | "zap"
-  | "stats";
+  | "stats"
+  | "screenshot"
+  | "404";
```
Comment (revolunet) [inline types/index.d.ts:27]:
```suggestion
  | "screenshot";
```

404 already at top

**Review by revolunet — APPROVED** [review]
